### ISSUE TITLE
Configure program via yaml file

### ISSUE THREAD

**Issue by fredi-arand** [fredi-arand/mMBa#1]
It would be nice to run the code as follows:

```sh
./mMBa someSettings.yaml
```

This would enable a lot of workflows.

I suggest to find and use a good third-party library.

Also, I would suggest using the "strict yaml" specification, see for example https://github.com/crdoconnor/strictyaml

The yaml file should contain a version, else I am open to suggestions:

```yaml
- version: 0.1
- input volume:
  - format: raw
  - resolution:
    - width: 256
    - height: 256
    - depth: 256
  # can be: 1 byte, 2 bytes, float 
  - voxel format: 1 byte
  - iso value: automatic # alternative: specify a value
  - endianness: little # little or big 
# ... etc
```
